title: My Jekyll Site
description: A simple site built with Jekyll
baseurl: "" # leave empty unless your site is in a subdirectory
url:     "https://github.com/aladddinaliyev/JavaScript-Debugger/blob/main/front/detrocelon.html"
